### ISSUE TITLE
The GPG public key in static/downloads/pubkey-9FBF85ED.asc is truncated

### ISSUE THREAD

**Issue by AlessandroMenti** [fntlnz/fntlnz.wtf#1]
The GPG public key in `static/downloads/pubkey-9FBF85ED.asc` starts with:

```
N PGP PUBLIC KEY BLOCK-----
```
instead of:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
```
(probably as a result of your static site generator interpreting the dashes as YAML front matter).

**Comment by fntlnz** [comment]
Thanks, this has been fixed. Also I updated with the new GPG key built thanks to your blog https://www.alessandromenti.it/blog/2017/01/transitioning-new-gpg-keypair.html
